controller_manager:
  ros__parameters:
    update_rate: 100  # 100Hz está bien para simulación

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    bobert_base_controller:
      type: diff_drive_controller/DiffDriveController

bobert_base_controller:
  ros__parameters:
    left_wheel_names: ["base_link_wheel_left_joint"]
    right_wheel_names: ["base_link_wheel_right_joint"]
    wheel_separation: 0.341
    wheel_radius: 0.1
    use_stamped_vel: false
    odom_frame_id: odom
    base_frame_id: base_footprint
    publish_rate: 50.0
    open_loop: false
    enable_odom_tf: false
    cmd_vel_timeout: 0.5

    linear:
      x:
        has_velocity_limits: true
        max_velocity: 2.0
        has_acceleration_limits: true
        max_acceleration: 4.0
        has_jerk_limits: false
    angular:
      z:
        has_velocity_limits: true
        max_velocity: 4.0
        has_acceleration_limits: true
        max_acceleration: 2.0

joint_state_broadcaster:
  ros__parameters:
    joints:
      - base_link_wheel_left_joint
      - base_link_wheel_right_joint
      - base_link_front_caster_joint        # ← agregar
      - base_link_rear_caster_joint         # ← agregar
      - front_caster_link_front_road_joint  # ← agregar
      - rear_caster_link_rear_road_joint    # ← agregar